name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: KyleGospo/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Los_Angeles
          config_presets: "@ocean-blue"
          retries: 3
          retries_delay: 300
          config_display: large
          plugin_activity: yes
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: rainbow
          plugin_languages_limit: 4
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_repositories: yes
          plugin_repositories_featured: ublue-os/bazzite, KyleGospo/City-17-Episode-One-Source
          plugin_repositories_affiliations: owner, collaborator
          plugin_licenses: yes
          plugin_sponsors: yes
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: ${{ secrets.STEAM_UID }}
          plugin_steam_sections: player
          plugin_steam_achievements_limit: 0
